#ifndef ASM_6502_H
#define ASM_6502_H

// Mnemonics
#define ASM_MN_LDA "LDA"
#define ASM_MN_LDX "LDX"
#define ASM_MN_LDY "LDY"
#define ASM_MN_STA "STA"
#define ASM_MN_STX "STX"
#define ASM_MN_STY "STY"
#define ASM_MN_TAX "TAX"
#define ASM_MN_TAY "TAY"
#define ASM_MN_TSX "TSX"
#define ASM_MN_TXA "TXA"
#define ASM_MN_TXS "TXS"
#define ASM_MN_TYA "TYA"
#define ASM_MN_PHA "PHA"
#define ASM_MN_PHP "PHP"
#define ASM_MN_PLA "PLA"
#define ASM_MN_PLP "PLP"
#define ASM_MN_ASL "ASL"
#define ASM_MN_LSR "LSR"
#define ASM_MN_ROL "ROL"
#define ASM_MN_ROR "ROR"
#define ASM_MN_AND "AND"
#define ASM_MN_BIT "BIT"
#define ASM_MN_EOR "EOR"
#define ASM_MN_ORA "ORA"
#define ASM_MN_ADC "ADC"
#define ASM_MN_CMP "CMP"
#define ASM_MN_CPX "CPX"
#define ASM_MN_CPY "CPY"
#define ASM_MN_SBC "SBC"
#define ASM_MN_DEC "DEC"
#define ASM_MN_DEX "DEX"
#define ASM_MN_DEY "DEY"
#define ASM_MN_INC "INC"
#define ASM_MN_INX "INX"
#define ASM_MN_INY "INY"
#define ASM_MN_BRK "BRK"
#define ASM_MN_JMP "JMP"
#define ASM_MN_JSR "JSR"
#define ASM_MN_RTI "RTI"
#define ASM_MN_RTS "RTS"
#define ASM_MN_BCC "BCC"
#define ASM_MN_BCS "BCS"
#define ASM_MN_BEQ "BEQ"
#define ASM_MN_BMI "BMI"
#define ASM_MN_BNE "BNE"
#define ASM_MN_BPL "BPL"
#define ASM_MN_BVC "BVC"
#define ASM_MN_BVS "BVS"
#define ASM_MN_CLC "CLC"
#define ASM_MN_CLD "CLD"
#define ASM_MN_CLI "CLI"
#define ASM_MN_CLV "CLV"
#define ASM_MN_SEC "SEC"
#define ASM_MN_SED "SED"
#define ASM_MN_SEI "SEI"
#define ASM_MN_NOP "NOP"

// Addressing modes
#define ASM_AM_ACCUMULATOR "A"
#define ASM_AM_IMPLIED ""
#define ASM_AM_IMMEDIATE "#$%x"
#define ASM_AM_ABSOLUTE "$%x"
#define ASM_AM_ABSOLUTE_X "$%x,X"
#define ASM_AM_ABSOLUTE_Y "$%x,Y"
#define ASM_AM_INDIRECT "($%x)"
#define ASM_AM_ZERO_PAGE "$%x"
#define ASM_AM_ZERO_PAGE_X "$%x,X"
#define ASM_AM_ZERO_PAGE_Y "$%x,Y"
#define ASM_AM_ZERO_PAGE_INDIRECT_X "($%x,X)"
#define ASM_AM_ZERO_PAGE_INDIRECT_Y "($%x),Y"
#define ASM_AM_RELATIVE "$%x"

#endif
